name: OpenWeather
options:
  bundleIdPrefix: com.OpenWeather
packages:
  Fork:
    url: https://github.com/0xLeif/Fork
    from: 1.0.0
  Scribe:
    url: https://github.com/0xLeif/Scribe
    from: 1.2.0
  o:
    url: https://github.com/0xOpenBytes/o
    from: 2.0.0
  c:
    url: https://github.com/0xOpenBytes/c
    from: 3.0.0
schemes:
  OpenWeather:
    build:
      targets:
        OpenWeather: all
        OpenWeatherUITests: [run, test]
  Screenshots:
    build:
      targets:
        OpenWeather: all
        OpenWeatherUITests: [run, test]
    test:
      targets:
        - OpenWeatherUITests
    run:
      environmentVariables:
        SCREENSHOTS: "YES"
targets:
  OpenWeather:
    scheme:
      testTargets:
        - OpenWeatherTests
    info:
      path: OpenWeather/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchScreen: [UILaunchScreen: []]
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
        - path: OpenWeather
          name: OpenWeather
          excludes:
            - "Swish"
    dependencies:
      - package: Fork
      - package: Scribe
      - package: o
      - package: c
    postCompileScripts:
      - name: Swiftlint
        script: |
          export PATH="$PATH:/opt/homebrew/bin"
          if which swiftlint > /dev/null; then
          swiftlint --config .swiftlint.yml
          else
          echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
        OpenWeatherdOnDependencyAnalysis: false

  OpenWeatherTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.0"
    sources: [OpenWeatherTests]
    info:
      path: OpenWeatherTests/Info.plist
    dependencies:
      - target: OpenWeather
  OpenWeatherUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "16.0"
    sources: [OpenWeatherUITests]
    info:
      path: OpenWeatherUITests/Info.plist
      properties:
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
    settings:
      TEST_TARGET_NAME: OpenWeather
      CODE_SIGN_STYLE: Automatic
      CURRENT_PROJECT_VERSION: 1
      MARKETING_VERSION: "1.0"
      TARGETED_DEVICE_FAMILY: 1
      GENERATE_INFOPLIST_FILE: YES
      PRODUCT_BUNDLE_IDENTIFIER: com.OpenWeather.UITests
