//
//  OpenWeather template generated by OpenBytes on 17/03/2023.
//
// Created by Ahmed Shendy.
//  DeviceWeatherSummary.swift
//

import SwiftUI

struct DeviceWeatherSummary: Identifiable {
    let id = UUID()
    let locationName: String
    let temperature: String
    let symbolName: String
}
