//
//  OpenWeather template generated by OpenBytes on 15/03/2023.
//
// Created by Ahmed Shendy.
//  DeviceWeather.swift
//

import SwiftUI

struct DeviceWeather: Identifiable {
    let id = UUID()
    let currentTemperature: Measurement<UnitTemperature>
    let realFeel: Measurement<UnitTemperature>
    let symbolName: String
    let wind: DeviceWind
    let hourlyForecast: [DeviceHourlyForecast]
}

struct DeviceWind {
    let direction: Measurement<UnitAngle>
    let speed: Measurement<UnitSpeed>
    let gust: Measurement<UnitSpeed>?
}

struct DeviceHourlyForecast {
    let date: Date
    let temperature: Measurement<UnitTemperature>
    let symbolName: String
}
