//
//  OpenWeather template generated by OpenBytes on 15/03/2023.
//
// Created by Ahmed Shendy.
//  DeviceWeather.swift
//

import SwiftUI

struct DeviceWeather: Identifiable {
    let id = UUID()
}
