//
//  OpenWeather template generated by OpenBytes on 22/03/2023.
//
// Created by Ahmed Shendy.
//  DeviceLocation.swift
//

import SwiftUI
import CoreLocation

struct DeviceLocation: Identifiable {
    let id = UUID()
    let name: String
    let location: CLLocation

    var lat: Double { location.coordinate.latitude }
    var long: Double { location.coordinate.longitude }
}
