//
//  OpenWeather template generated by OpenBytes on 15/03/2023.
//
// Created by Ahmed Shendy.
//  LocationProviding.swift
//

import Foundation
import CoreLocation

protocol LocationProviding {
    func locationName(for location: CLLocation) async throws -> String
    func locations(for address: String) async throws -> [DeviceLocation]
}
