//
//  OpenWeather template generated by OpenBytes on 15/03/2023.
//
// Created by Ahmed Shendy.
//  LocationProviding+Models.swift
//

import Foundation

struct LocationNameResponse {
    let name: String
}
