//
//  OpenWeather template generated by OpenBytes on 15/03/2023.
//
// Created by Ahmed Shendy.
//  WeatherProviding+Models.swift
//

import Foundation
import WeatherKit

struct WeatherResponse {
    let weather: Weather
}
