//
//  OpenWeather template generated by OpenBytes on 15/03/2023.
//
// Created by Ahmed Shendy.
//  LocationProviding+Default.swift
//

import Foundation
import CoreLocation

enum LocationProvidingError: LocalizedError {
    case noSuchPlace
    case failure(reason: String)

    var errorDescription: String? {
        switch self {
        case .noSuchPlace:
            return "\(#fileID): No such place"
        case .failure(let reason):
            return "\(#fileID): Failure: \(reason)"
        }
    }
}
