//
//  OpenWeather template generated by OpenBytes on 15/03/2023.
//
// Created by Ahmed Shendy.
//  MockWeatherService.swift
//

import Foundation

final class MockWeatherService: WeatherNetworking {
    
}
