//
//  OpenWeather template generated by OpenBytes on 15/03/2023.
//
// Created by Ahmed Shendy.
//  WeatherService.swift
//

import Foundation
import WeatherKit

final class WeatherService: WeatherNetworking {
    let service: WeatherKit.WeatherService = .shared
}
