//
//  OpenWeather template generated by OpenBytes on 30/04/2023.
//
// Created by Ahmed Shendy.
//  DatabaseServiceTests.swift
//

import XCTest
@testable import OpenWeather

final class DatabaseServiceTests: XCTestCase {
    func testDatabaseSchema() async throws {
        let sut: DatabaseService  = try SQLiteDatabaseService.empty()

        try XCTAssert(sut.tableExists("favorites"))
    }
}
