//
//  OpenWeather template generated by OpenBytes on 30/04/2023.
//
// Created by Ahmed Shendy.
//  SQLiteDatabaseServiceTests.swift
//

import XCTest
@testable import OpenWeather

final class SQLiteDatabaseServiceTests: XCTestCase {
    func testFavoritesSchema() async throws {
        let sut = try SQLiteDatabaseService.empty()

        let tableName: String = "favorites"
        let tableExists = try await sut.tableExists(tableName)

        XCTAssert(tableExists)

        let columns = try await sut.columns(in: tableName)

        XCTAssertEqual(columns, ["id", "name", "lat", "long", "created_at"])
    }

    func testinsertOneFavorite() async throws {
        let sut = try SQLiteDatabaseService.empty()

        let location: DeviceLocation = .init(
            name: "London",
            location: .london
        )

        let locationDoesNotExist = try await sut.favoriteExists(location) == false

        XCTAssert(locationDoesNotExist)

        try await sut.insertOneFavorite(location)

        let foundLocation = try await sut.fetchOneFavorite(location)

        XCTAssert(location == foundLocation)
    }

    func testRemoveFavoriteLocation() async throws {
        let sut = try SQLiteDatabaseService.empty()

        let location: DeviceLocation = .init(
            name: "London",
            location: .london
        )

        try await sut.insertOneFavorite(location)

        let locationExists = try await sut.favoriteExists(location)

        XCTAssert(locationExists)

        try await sut.deleteOneFavorite(location)

        let locationDoesNotExist = try await sut.favoriteExists(location) == false

        XCTAssert(locationDoesNotExist)
    }
}

extension SQLiteDatabaseServiceTests {
    private static func empty() throws -> SQLiteDatabaseService {
        let dbQueue = try DatabaseQueue(
            configuration: SQLiteDatabaseService.makeConfiguration()
        )

        return try SQLiteDatabaseService(dbQueue)
    }
}
