//
//  OpenWeather template generated by OpenBytes on 30/04/2023.
//
// Created by Ahmed Shendy.
//  DatabaseService.swift
//

import Foundation

protocol DatabaseService {
    static func empty() throws -> Self

    func tableExists(_ name: String) async throws -> Bool
    func columns(in name: String) async throws -> [String]

    // Favorites Table
    func favoriteExists(by id: String) async throws -> Bool
    func findFavoriteLocation(by id: String) async throws -> LocationData?
    func insertFavoriteLocation(_ location: LocationData) async throws
    func deleteFavoriteLocation(by id: String) async throws
}
