//
//  OpenWeather template generated by OpenBytes on 30/04/2023.
//
// Created by Ahmed Shendy.
//  DatabaseService.swift
//

import Foundation

protocol DatabaseService {
    static func empty() throws -> Self

    func tableExists(_ name: String) async throws -> Bool

    func favoriteExists(by id: String) async throws -> Bool
    func findFavoriteLocation(by id: String) async throws -> LocationData?
    func saveFavoriteLocation(_ location: LocationData) async throws
}
