//
//  OpenWeather template generated by OpenBytes on 30/04/2023.
//
// Created by Ahmed Shendy.
//  DatabaseService.swift
//

import Foundation

protocol DatabaseService {
    static func empty() throws -> Self

    func tableExists(_ name: String) throws -> Bool
}
