//
//  OpenWeather template generated by OpenBytes on 24/03/2023.
//
// Created by Ahmed Shendy.
//  LocationResultItem.swift
//

import SwiftUI

struct LocationResultItem: View {
    let name: String

    var body: some View {
        VStack {
            Text(name)

            // ...
        }
    }
}
