//
//  OpenWeather template generated by OpenBytes on 31/03/2023.
//
// Created by Ahmed Shendy.
//  LocationAdapterTest.swift
//

import XCTest
@testable import OpenWeather

final class LocationAdapterTest: XCTestCase {
    func testAdapter() {
        let networkModel = LocationData(
            name: "London",
            location: .london
        )

        let deviceModel = LocationAdapter.device(from: networkModel)

        XCTAssertEqual(deviceModel.name, networkModel.name)
        XCTAssertEqual(deviceModel.location, networkModel.location)
    }
}
