//
//  OpenWeather template generated by OpenBytes on 16/05/2023.
//
// Created by Ahmed Shendy.
//  LocationEquating.swift
//

import Foundation

func == (lhs: DeviceLocation, rhs: LocationData) -> Bool {
    rhs == lhs
}

func == (lhs: LocationData, rhs: DeviceLocation) -> Bool {
    lhs.name == rhs.name
    && lhs.lat == rhs.latitude
    && lhs.long == rhs.longitude
}
