//
//  OpenWeather template generated by OpenBytes on 22/03/2023.
//
// Created by Ahmed Shendy.
//  LocationData.swift
//

import GRDB
import Foundation
import CoreLocation

struct LocationData: Codable {
    let name: String
    let lat: Double
    let long: Double

    var location: CLLocation { .init(latitude: lat, longitude: long) }
}

extension LocationData: TableRecord, FetchableRecord {
    static var databaseTableName: String = "favorites"
}

extension LocationData: CustomStringConvertible {
    var description: String {
        """
        {
            name: \(name),
            latitude: \(lat),
            longitude: \(long)
        }
        """
    }
}

extension LocationData: Equatable {
    static func == (lhs: Self, rhs: Self) -> Bool {
        lhs.name == rhs.name
        && lhs.lat == rhs.lat
        && lhs.long == rhs.long
    }
}
