//
//  OpenWeather template generated by OpenBytes on 22/03/2023.
//
// Created by Ahmed Shendy.
//  LocationData.swift
//

import Foundation
import CoreLocation

struct LocationData {
    let name: String
    let location: CLLocation
}
