//
//  OpenWeather template generated by OpenBytes on 22/03/2023.
//
// Created by Ahmed Shendy.
//  NetworkLocation.swift
//

import Foundation
import CoreLocation

struct NetworkLocation {
    let name: String
    let location: CLLocation
}
