//
//  OpenWeather template generated by OpenBytes on 4/25/23.
//
// Created by Leif.
//  OpenWeatherMapWeather.swift
//

import Foundation

struct OpenWeatherMapWeather: Codable {
    struct CurrentWeather: Codable {
        let temp: Double
        let feels_like: Double
    }

    struct Wind: Codable {
        let deg: Double
        let speed: Double
        let gust: Double?
    }

    let main: CurrentWeather
    let wind: Wind
}
