//
//  OpenWeather template generated by OpenBytes on 16/05/2023.
//
// Created by Ahmed Shendy.
//  Array+OpenWeather.swift
//

import Foundation

extension Array where Element == LocationData {
    func mapToDevice() -> [DeviceLocation] {
        self.map(LocationAdapter.device(from:))
    }
}

extension Array where Element == DeviceLocation {
    func mapToData() -> [LocationData] {
        self.map(LocationAdapter.data(from:))
    }
}
