//
//  OpenWeather template generated by OpenBytes on 04/04/2023.
//
// Created by Ahmed Shendy.
//  Measurement+OpenWeather.swift
//

import Foundation

extension Measurement where UnitType : Dimension {
    var abbreviatedAsProvided: String {
        formatted(.measurement(width: .abbreviated, usage: .asProvided))
    }
}
