//
//  OpenWeather template generated by OpenBytes on 02/04/2023.
//
// Created by Ahmed Shendy.
//  FavoritesViewModelTests.swift
//

import Test
import XCTest
import CoreLocation
@testable import OpenWeather

final class FavoritesViewModelTests: XCTestCase {

    func testGetWeatherSummary() async throws {
        func testGetWeatherSummary(on sut: FavoritesViewModel, for locations: [CLLocation]) async throws {
            sut.getWeatherSummary(for: locations)

            try await Waiter(sut).wait(for: \.value.content.favorites) { summaries in
                summaries.count == locations.count
            }

            XCTAssertEqual(sut.content.favorites.count, locations.count)
        }

        let sut: FavoritesViewModel = .mock

        try await testGetWeatherSummary(on: sut, for: [.london, .cairo])
        try await testGetWeatherSummary(on: sut, for: [])
    }
}
