//
//  OpenWeather template generated by OpenBytes on 23/03/2023.
//
// Created by Ahmed Shendy.
//  LocationAdapter.swift
//

import Foundation
import CoreLocation

enum LocationAdapter: Adaptable {
    static func device(from: LocationData) -> DeviceLocation {
        return DeviceLocation(
            name: from.name,
            location: from.location
        )
    }
}
