//
//  OpenWeather template generated by OpenBytes on 15/03/2023.
//
// Created by Ahmed Shendy.
//  WeatherAdapter.swift
//

import Foundation
import WeatherKit

enum WeatherAdapter: Adaptable {
    static func device(from: Weather) throws -> DeviceWeather {
        return DeviceWeather()
    }
}
