//
//  OpenWeather template generated by OpenBytes on 22/03/2023.
//
// Created by Ahmed Shendy.
//  SearchViewModel.swift
//

import Foundation
import CoreLocation

final class SearchViewModel: ObservableObject, ErrorHandling {
    private var locationProviding: LocationProviding
    private var task: Task<Void, Never>?

    var errorHandler: ErrorHandler

    @Published var result: [DeviceLocation] = []

    init(
        locationProviding: LocationProviding,
        errorHandler: ErrorHandler = ErrorHandler(
            plugins: [
                ToastErrorPlugin()
            ]
        )
    ) {
        self.locationProviding = locationProviding
        self.errorHandler = errorHandler
    }

    func getLocations(query: String) {
        task?.cancel()

        task = Task {
            let result = try? await locationProviding.locations(for: query)

            await MainActor.run {
                self.result = result ?? []
            }
        }
    }
}
