//
//  OpenWeather template generated by OpenBytes on 15/03/2023.
//
// Created by Ahmed Shendy.
//  CurrentWeatherProvider.swift
//

import Foundation
import CoreLocation

protocol CurrentWeatherProviding {
    mutating func currentWeather(
        for location: CLLocation
    ) async throws -> DeviceWeather
}

struct CurrentWeatherProvider: CurrentWeatherProviding, WeatherProviding {
    func currentWeather(for location: CLLocation) async throws -> DeviceWeather {
        let response = try await weather(for: location)

        return try WeatherAdapter.device(from: response.weather)
    }
}

struct MockCurrentWeatherProvider: CurrentWeatherProviding, WeatherProviding {
    func currentWeather(for location: CLLocation) async throws -> DeviceWeather {
        return DeviceWeather(
            currentTemperature: .init(value: 0, unit: .celsius),
            realFeel: .init(value: 0, unit: .celsius),
            wind: DeviceWind(
                direction: .init(value: 0, unit: .degrees),
                speed: .init(value: 0, unit: .kilometersPerHour),
                gust: nil),
            hourlyForecast: [
                DeviceHourlyForecast(
                    date: .now,
                    temperature: .init(value: 0, unit: .celsius),
                    symbolName: "Cloud"
                )
            ]
        )
    }
}
