//
//  OpenWeather template generated by OpenBytes on 15/03/2023.
//
// Created by Ahmed Shendy.
//  CurrentWeatherProvider.swift
//

import Foundation
import CoreLocation

protocol CurrentWeatherProviding {
    mutating func currentWeather(
        for location: CLLocation
    ) async throws -> DeviceWeather
}

struct CurrentWeatherProvider: CurrentWeatherProviding, WeatherProviding {
    func currentWeather(for location: CLLocation) async throws -> DeviceWeather {
        let response: WeatherResponse = try await currentWeather(for: location)

        return try WeatherAdapter.device(from: response.weather)
    }
}

struct MockCurrentWeatherProvider: CurrentWeatherProviding, WeatherProviding {
    func currentWeather(for location: CLLocation) async throws -> DeviceWeather {
        return DeviceWeather()
    }
}
